# Generated by Django 4.1.1 on 2022-09-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderedDate',
            new_name='created_at',
        ),
    ]
