# Generated by Django 4.1.1 on 2022-09-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('img1', models.ImageField(blank=True, default='product/default.png', null=True, upload_to='product/')),
                ('img2', models.ImageField(blank=True, default='product/default.png', null=True, upload_to='product/')),
            ],
        ),
    ]
